[project]
name = "dailyarxivsubscription"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "feedparser>=6.0.11",
    "pytz>=2025.2",
    "pyyaml>=6.0.2",
    "requests>=2.32.4",
]
